version: '3.1'

services:

  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./mysqldata:/var/lib/mysql
volumes:
  mysqldata:
